# Generated by Django 4.1.3 on 2023-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persnol_details',
            name='profile_img',
        ),
        migrations.AlterField(
            model_name='persnol_details',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Bihar', 'Bihar')], max_length=50),
        ),
    ]
