# Generated by Django 4.1.3 on 2023-04-17 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
                ('own_referal', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('referal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='referral_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50)),
                ('referred_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_referral_set', to='myapp.referral')),
                ('referrer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_referral_set', to='myapp.referral')),
            ],
        ),
        migrations.CreateModel(
            name='commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('commission_amount', models.IntegerField()),
                ('commission_date', models.DateField(null=True)),
                ('referral_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission_set', to='myapp.referral_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_commission_set', to='myapp.referral')),
            ],
        ),
        migrations.CreateModel(
            name='commision_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.referral')),
            ],
        ),
    ]
