# Generated by Django 4.1.3 on 2023-04-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_commision_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
