# Generated by Django 4.1.3 on 2023-04-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_commission_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='name',
        ),
    ]
